# redirect docs
[[redirects]]
  from = "/docs"
  to = "https://opentargets.gitbook.io/open-targets-genetics-documentation"
  status = 302
  force = true

# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
