# redirect docs
[[redirects]]
  from = "/docs/*"
  to = "https://opentargets.gitbook.io/open-targets-genetics-documentation/:splat"
  status = 200

# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
