query BrowserTableQuery(
    $chromosome: String
    $start: Int
    $end: Int
    $g2VMustHaves: [String]
    $g2VScore: [Float]
    $r2: [Float]
    $gwasPValue: [Float]
    $selectedId: String
    $selectedType: String
    $limit: Int
    $offset: Int
) {
    locusTable(
        chromosome: $chromosome
        start: $start
        end: $end
        g2VMustHaves: $g2VMustHaves
        g2VScore: $g2VScore
        r2: $r2
        gwasPValue: $gwasPValue
        selectedId: $selectedId
        selectedType: $selectedType
        limit: $limit
        offset: $offset
    ) {
        total
        offset
        limit
        rows {
            index
            geneId
            geneSymbol
            geneChromosome
            geneTss
            vId
            variantChromosome
            vPos
            lvId
            efoId
            efoName
            otG2VScore
            gtexMaxTissue
            gtexMaxValue
            vep
            vepTerms
            gtex
            pchic
            fantom5
            dhs
            nearest
            r2
            gwasPValue
            gwasOddsRatio
            gwasBeta
            gwasSize
            gwasPMId
            gwasStudy
        }
    }
}
