query DiseaseTableQuery($efoId: String, $offset: Int, $limit: Int) {
    diseaseTable(efoId: $efoId, limit: $limit, offset: $offset) {
        total
        offset
        limit
        rows {
            index
            geneId
            geneSymbol
            geneChromosome
            geneTss
            vId
            variantChromosome
            vPos
            lvId
            efoId
            efoName
            otG2VScore
            gtexMaxTissue
            gtexMaxValue
            vep
            vepTerms
            gtex
            pchic
            fantom5
            dhs
            nearest
            r2
            gwasPValue
            gwasOddsRatio
            gwasBeta
            gwasSize
            gwasPMId
            gwasStudy
        }
    }
}
